# Generated by Django 6.0.1 on 2026-01-18 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompagniePetrolier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite', models.DecimalField(decimal_places=3, max_digits=15)),
                ('barremage', models.JSONField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CARBURANT', 'Carburant'), ('LUBRIFIANT', 'Lubrifiant')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarqueCompagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('compagnie_petrolier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.compagniepetrolier')),
            ],
        ),
        migrations.CreateModel(
            name='Pistolet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('cuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.cuve')),
            ],
        ),
        migrations.AddField(
            model_name='cuve',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.produit'),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('informations', models.JSONField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compagnie_petrolier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.compagniepetrolier')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.marquecompagnie')),
            ],
        ),
        migrations.AddField(
            model_name='cuve',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.station'),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.profil')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='gerant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.utilisateur'),
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ACHAT', 'Achat'), ('VENTE', 'Vente'), ('INVENTAIRE', 'Inventaire')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date_mouvement', models.DateTimeField()),
                ('infos', models.JSONField(blank=True, null=True)),
                ('cuve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock.cuve')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.produit')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.station')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='StockStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.produit')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.station')),
            ],
            options={
                'unique_together': {('station', 'produit')},
            },
        ),
    ]
