# Generated by Django 6.0.1 on 2026-01-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
        migrations.AlterField(
            model_name='station',
            name='gerant',
            field=models.ForeignKey(help_text='Un gérant peut gérer une ou plusieurs stations', on_delete=django.db.models.deletion.CASCADE, to='gestion_stock.utilisateur'),
        ),
    ]
