# Generated by Django 6.0.1 on 2026-01-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock', '0002_alter_station_options_alter_station_gerant'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='responsable_zone',
            field=models.ForeignKey(blank=True, help_text='Responsable de zone pour cette station', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations_supervisees', to='gestion_stock.utilisateur'),
        ),
        migrations.AlterField(
            model_name='station',
            name='gerant',
            field=models.ForeignKey(help_text='Un gérant peut gérer une ou plusieurs stations', on_delete=django.db.models.deletion.CASCADE, related_name='stations_gerees', to='gestion_stock.utilisateur'),
        ),
    ]
